// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FBOLinx.DB.Models
{
    public partial class AcukwikServicesOfferedDefaults : FBOLinxBaseEntityModel<int>
    {
        public int AcukwikServicesOfferedId { get; set; }
        public string Service { get; set; }
        public bool? Omit { get; set; }
    }
}