// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FBOLinx.DB
{
    public partial class AircraftHexTailMapping
    {
        [Key]
        [Column("OID")]
        public int Oid { get; set; }
        [Required]
        [StringLength(25)]
        public string AircraftHexCode { get; set; }
        [StringLength(25)]
        public string TailNumber { get; set; }
    }
}