// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using FBOLinx.DB.Models;

namespace FBOLinx.DB
{
    public partial class AircraftHexTailMapping : FBOLinxBaseEntityModel<int>
    {
        [Required]
        [StringLength(25)]
        public string AircraftHexCode { get; set; }
        [StringLength(25)]
        public string TailNumber { get; set; }
    }
}