// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using FBOLinx.DB.Models;

namespace FBOLinx.DB.Models
{
    public partial class AircraftHexTailMapping : FBOLinxBaseEntityModel<int>
    {
        [Required]
        [StringLength(25)]
        public string AircraftHexCode { get; set; }

        [StringLength(25)]
        public string TailNumber { get; set; }

        [Column("FAAAircraftMakeModelCode")]
        [StringLength(50)]
        public string FAAAircraftMakeModelCode { get; set; }

        [Column("FAARegisteredOwner")]
        [StringLength(100)]
        public string FAARegisteredOwner { get; set; }
    }
}