// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace FBOLinx.DB
{
    public partial class AirportWatchChangeTracker
    {
        public int Oid { get; set; }
        public int? LiveDataRecords { get; set; }
        public int? HistoricalDataRecords { get; set; }
        public int? TailNumberRecords { get; set; }
        public DateTime? DateTimeAppliedUtc { get; set; }
    }
}