// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FBOLinx.DB.Models
{
    [Index("AirportWatchHistoricalDataId", Name = "INX_AirportWatchHistoricalParking_AirportWatchHistoricalDataID")]
    public class AirportWatchHistoricalParking : FBOLinxBaseEntityModel<int>
    {
        [Column("AirportWatchHistoricalDataID")]
        public int AirportWatchHistoricalDataId { get; set; }
        [Column("AcukwikFBOHandlerID")]
        public int AcukwikFbohandlerId { get; set; }
        [Column("DateCalculatedUTC", TypeName = "datetime")]
        public DateTime? DateCalculatedUtc { get; set; }
        public bool? IsConfirmed { get; set; }

        #region Relationships
        [ForeignKey(nameof(AirportWatchHistoricalDataId))]
        [InverseProperty("AirportWatchHistoricalParking")]
        public AirportWatchHistoricalData AirportWatchHistoricalData { get; set; }
        #endregion
    }
}