// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using FBOLinx.DB.Models;
using Microsoft.EntityFrameworkCore;

namespace FBOLinx.DB.Models
{
    public class AirportWatchDistinctBoxes : FBOLinxBaseEntityModel<int>
    {
        [StringLength(50)]
        [Unicode(false)]
        public string BoxName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastLiveDateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastHistoricDateTime { get; set; }
        [StringLength(10)]
        public string AirportICAO { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }
}