// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FBOLinx.DB.Models
{
    [Index("CustomerAircraftId", Name = "INX_CustomerAircraftNotes_CustomerAircraftID")]
    [Table("CustomerAircraftNotes")]
    public partial class CustomerAircraftNote
    {
        [Key]
        [Column("OID")]
        public int Oid { get; set; }
        [Column("CustomerAircraftID")]
        public int CustomerAircraftId { get; set; }
        [Column("FBOID")]
        public int? FboId { get; set; }
        [Unicode(false)]
        public string Notes { get; set; }
        [Column("LastUpdatedUTC", TypeName = "datetime")]
        public DateTime? LastUpdatedUtc { get; set; }
        [Column("LastUpdatedByUserID")]
        public int? LastUpdatedByUserId { get; set; }

        #region Relationships
        [ForeignKey(nameof(CustomerAircraftId))]
        [InverseProperty("Notes")]
        public virtual CustomerAircrafts CustomerAircraft { get; set; }
        
        #endregion
    }
}