// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FBOLinx.DB.Models
{
    [Index("CustomerInfoByGroupId", Name = "INX_CustomerInfoByGroupNotes_CustomerInfoByGroupID")]
    [Table("CustomerInfoByGroupNotes")]
    public partial class CustomerInfoByGroupNote
    {
        [Key]
        [Column("OID")]
        public int Oid { get; set; }
        [Column("CustomerInfoByGroupID")]
        public int CustomerInfoByGroupId { get; set; }
        [Column("FBOID")]
        public int? Fboid { get; set; }
        [Unicode(false)]
        public string Notes { get; set; }
        [Column("LastUpdatedUTC", TypeName = "datetime")]
        public DateTime? LastUpdatedUtc { get; set; }
        [Column("LastUpdatedByUserID")]
        public int? LastUpdatedByUserId { get; set; }

        #region Relationships
        [ForeignKey(nameof(CustomerInfoByGroupId))]
        [InverseProperty("Notes")]
        public virtual CustomerInfoByGroup CustomerInfoByGroup { get; set; }
        #endregion
    }
}