// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using FBOLinx.DB.Models;

namespace FBOLinx.Web
{
    [Table("FBOFeesAndTaxes")]
    public partial class FboFeesAndTaxes
    {
        [Key]
        [Column("OID")]
        public int Oid { get; set; }
        [Column("FBOID")]
        public int Fboid { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public FBOLinx.Core.Enums.FeeCalculationTypes? CalculationType { get; set; }
        public double Value { get; set; }
        public FBOLinx.Core.Enums.FlightTypeClassifications? FlightTypeClassification { get; set; }
        public FBOLinx.Core.Enums.ApplicableTaxFlights? DepartureType { get; set; }
        public FBOLinx.Core.Enums.FeeCalculationApplyingTypes? WhenToApply { get; set; }

        [NotMapped]
        public bool IsOmitted { get;set; }

        #region Relationships
        [InverseProperty("FboFeeAndTax")]
        public List<FboFeeAndTaxOmitsByCustomer> OmitsByCustomer { get; set; }

        [InverseProperty("FboFeeAndTax")]
        public List<FboFeeAndTaxOmitsByPricingTemplate> OmitsByPricingTemplate { get; set; }
        #endregion

        public double GetCalculatedValue(double basePrice, double allInPrice)
        {
            if (CalculationType == FBOLinx.Core.Enums.FeeCalculationTypes.FlatPerGallon)
                return Value;
            if (CalculationType == FBOLinx.Core.Enums.FeeCalculationTypes.Percentage)
                return (((Value / 100.0)) * basePrice);
            if (CalculationType == FBOLinx.Core.Enums.FeeCalculationTypes.PercentageOfTotal)
                return (((Value / 100.0)) * allInPrice);
            return Value;
        }
    }
}