// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FBOLinx.DB.Models
{
    public partial class FbolinxFileData
    {
        [Key]
        [Column("OID")]
        public int Oid { get; set; }
        [StringLength(255)]
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
        [StringLength(255)]
        public string ContentType { get; set; }
    }
}
