// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FBOLinx.DB.Models
{
    public partial class FboLinxImageFileData
    {
        [Key]
        [Column("OID")]
        public int Oid { get; set; }
        public byte[] FileData { get; set; }
        [StringLength(200)]
        public string FileName { get; set; }
        [StringLength(100)]
        public string ContentType { get; set; }
        public int FboId { get; set; }
        public int GroupId { get; set; }
    }
}
