// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FBOLinx.Core.Enums;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FBOLinx.DB.Models
{
    public partial class IntegrationPartners
    {
        [Key]
        [Column("OID")]
        public int Oid { get; set; }
        [Required]
        [StringLength(255)]
        public string PartnerName { get; set; }
        public IntegrationPartnerTypes PartnerType { get; set; }
        public short Affiliation { get; set; }
        [Column("APIKey")]
        public Guid Apikey { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public Guid? PartnerId { get; set; }
        public TrustLevels? TrustLevel { get; set; }
    }
}