// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FBOLinx.DB.Models
{
    public partial class IntegrationStatus
    {
        [Key]
        [Column("OID")]
        public int Oid { get; set; }
        public int IntegrationPartnerId { get; set; }
        public int FboId { get; set; }
        public bool IsActive { get; set; }
    }
}