// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FBOLinx.DB.Models
{
    public partial class IntegrationUpdatePricingLog : FBOLinxBaseEntityModel<int>
    {
        public string Request { get; set; }
        public string Response { get; set; }
        public int? FboId { get; set; }
        public DateTime DateTimeRecorded { get; set; }
    }
}