// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FBOLinx.DB.Models
{
    //[Index(nameof(FboId), nameof(CreatedDate), Name = "INX_MissedQuoteLog_FboIdCreatedDate")]
    public partial class MissedQuoteLog : FBOLinxBaseEntityModel<int>
    {
        public int? FboId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CustomerId { get; set; }
        public bool? Emailed { get; set; }
        public string Debugs { get; set; }
    }
}