// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FBOLinx.DB.Models
{
    [Index("FuelerLinxTransactionId", Name = "INX_OrderDetails_FuelerLinxTransactionId", IsUnique = true)]
    public partial class OrderDetails : FBOLinxBaseEntityModel<int>
    {
        public int FuelerLinxTransactionId { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string ConfirmationEmail { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string FuelVendor { get; set; }
    }
}