// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FBOLinx.DB.Models
{
    [Index("AssociatedServiceOrderId", Name = "INX_OrderNotes_AssociatedServiceOrderId")]
    [Index("AssociatedFuelOrderId", Name = "INX_OrderNotes_AssociatedFuelOrderId")]
    [Index("AssociatedFuelerLinxTransactionId", Name = "INX_OrderNotes_AssociatedFuelerLinxTransactionId")]
    [Table("OrderNotes")]
    public partial class OrderNote : FBOLinxBaseEntityModel<int>
    {
        public int AssociatedFuelOrderId { get; set; }
        public int AssociatedServiceOrderId { get; set; }
        public int AssociatedFuelerLinxTransactionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateAdded { get; set; }
        public string? Note { get; set; }
        [Column("AddedByUserID")]
        public int? AddedByUserId { get; set; }
        [StringLength(255)]
        public string? AddedByName { get; set; }
        public string? TimeZone { get; set; }
    }
}