// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using FBOLinx.DB.Models;
using Microsoft.EntityFrameworkCore;

namespace FBOLinx.DB.Models
{
    [Index("AssociatedFuelOrderId", Name = "INX_ServiceOrders_AssociatedFuelOrderID")]
    [Index("CustomerId", "ServiceDateTimeUtc", Name = "INX_ServiceOrders_CustomerID_ServiceDateTimeUTC")]
    [Index("Fboid", "ServiceDateTimeUtc", Name = "INX_ServiceOrders_FBOID_ServiceDateTimeUTC")]
    [Table("ServiceOrders")]
    public partial class ServiceOrder
    {
        [Key]
        [Column("OID")]
        public int Oid { get; set; }
        [Column("FBOID")]
        public int Fboid { get; set; }
        [Column("GroupID")]
        public int GroupId { get; set; }
        [Column("CustomerID")]
        public int CustomerId { get; set; }
        [Column("ServiceDateTimeUTC", TypeName = "datetime")]
        public DateTime ServiceDateTimeUtc { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string TailNumber { get; set; }
        [Column("AssociatedFuelOrderID")]
        public int? AssociatedFuelOrderId { get; set; }

        #region Relationships
        [ForeignKey(nameof(AssociatedFuelOrderId))]
        [InverseProperty(nameof(FuelReq.ServiceOrder))]
        public FuelReq AssociatedFuelOrder { get; set; }

        [InverseProperty(nameof(ServiceOrderItem.ServiceOrder))]
        public ICollection<ServiceOrderItem> ServiceOrderItems { get; set; }
        #endregion
    }
}