// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FBOLinx.DB.Models
{
    [Index("ServiceOrderId", Name = "INX_ServiceOrderItems_ServiceOrderID")]
    [Table("ServiceOrderItems")]
    public partial class ServiceOrderItem
    {
        [Key]
        [Column("OID")]
        public long Oid { get; set; }
        [Column("ServiceOrderID")]
        public int ServiceOrderId { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string ServiceName { get; set; }
        public int Quantity { get; set; }
        public bool? IsCompleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CompletionDateTimeUtc { get; set; }
        [Column("CompletedByUserID")]
        public int? CompletedByUserId { get; set; }
        [StringLength(255)]
        public string CompletedByName { get; set; }

        #region Relationships
        [ForeignKey(nameof(ServiceOrderId))]
        [InverseProperty(nameof(Models.ServiceOrder.ServiceOrderItems))]
        public ServiceOrder ServiceOrder { get; set; }
        #endregion
    }
}