// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using FBOLinx.DB.Models;
using Microsoft.EntityFrameworkCore;

namespace FBOLinx.DB.Models
{
    [Index("FuelerLinxTransactionId", Name = "INX_ServiceOrders_FuelerLinxTransactionID")]
    [Index("AssociatedFuelOrderId", Name = "INX_ServiceOrders_AssociatedFuelOrderID")]
    [Index("CustomerInfoByGroupId", "ArrivalDateTimeUtc", Name = "INX_ServiceOrders_CustomerInfoByGroupID_ArrivalDateTimeUTC")]
    [Index("Fboid", "ArrivalDateTimeUtc", Name = "INX_ServiceOrders_FBOID_ArrivalDateTimeUTC")]
    [Table("ServiceOrders")]
    public partial class ServiceOrder
    {
        [Key]
        [Column("OID")]
        public int Oid { get; set; }
        [Column("FBOID")]
        public int Fboid { get; set; }
        [Column("GroupID")]
        public int GroupId { get; set; }
        [Column("CustomerInfoByGroupID")]
        public int CustomerInfoByGroupId { get; set; }
        [Column("ArrivalDateTimeUTC", TypeName = "datetime")]
        public DateTime ArrivalDateTimeUtc { get; set; }
        [Column("DepartureDateTimeUTC", TypeName = "datetime")]
        public DateTime? DepartureDateTimeUtc { get; set; }
        [Column("CustomerAircraftID")]
        public int CustomerAircraftId { get; set; }
        [Column("AssociatedFuelOrderID")]
        public int? AssociatedFuelOrderId { get; set; }
        [Column("FuelerLinxTransactionID")]
        public int? FuelerLinxTransactionId { get; set; }

        #region Relationships
        [ForeignKey(nameof(AssociatedFuelOrderId))]
        [InverseProperty(nameof(FuelReq.ServiceOrder))]
        public FuelReq AssociatedFuelOrder { get; set; }

        [InverseProperty(nameof(ServiceOrderItem.ServiceOrder))]
        public ICollection<ServiceOrderItem> ServiceOrderItems { get; set; }

        [ForeignKey(nameof(CustomerInfoByGroupId))]
        [InverseProperty(nameof(Models.CustomerInfoByGroup.ServiceOrders))]
        public CustomerInfoByGroup CustomerInfoByGroup { get; set; }

        [ForeignKey(nameof(CustomerAircraftId))]
        [InverseProperty(nameof(Models.CustomerAircrafts.ServiceOrders))]
        public CustomerAircrafts CustomerAircraft { get; set; }
        #endregion
    }
}