// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FBOLinx.Web
{
    public partial class AircraftSpecifications
    {
        [Key]
        [Column("OID")]
        public int Oid { get; set; }
        [Column("AircraftID")]
        public int? AircraftId { get; set; }
        [Column("MODEL NAME")]
        [StringLength(255)]
        public string ModelName { get; set; }
        [Column("Fuselage Dimensions Length (ft)")]
        public double? FuselageDimensionsLengthFt { get; set; }
        [Column("Fuselage Dimensions Height (ft)")]
        public double? FuselageDimensionsHeightFt { get; set; }
        [Column("Fuselage Dimensions Wing Span (ft)")]
        public double? FuselageDimensionsWingSpanFt { get; set; }
        [Column("Cabin Dimensions Length (ft/inches)")]
        [StringLength(255)]
        public string CabinDimensionsLengthFtInches { get; set; }
        [Column("Cabin Dimensions Height (ft/inches)")]
        [StringLength(255)]
        public string CabinDimensionsHeightFtInches { get; set; }
        [Column("Cabin Dimensions Width (ft/inches)")]
        [StringLength(255)]
        public string CabinDimensionsWidthFtInches { get; set; }
        [Column("Crew Configuration")]
        public double? CrewConfiguration { get; set; }
        [Column("Passenger Configuration")]
        public double? PassengerConfiguration { get; set; }
        [Column("Pressurization (psi)")]
        public double? PressurizationPsi { get; set; }
        [Column("Fuel Capacity Standard (lbs)")]
        public double? FuelCapacityStandardLbs { get; set; }
        [Column("Fuel Capacity Standard (gal)")]
        public double? FuelCapacityStandardGal { get; set; }
        [Column("Fuel Capacity Optional (lbs)")]
        public double? FuelCapacityOptionalLbs { get; set; }
        [Column("Fuel Capacity Optional (gal)")]
        public double? FuelCapacityOptionalGal { get; set; }
        [Column("Max# Ramp Weight (lbs)")]
        public double? MaxRampWeightLbs { get; set; }
        [Column("Max Takeoff Weight (lbs)")]
        public double? MaxTakeoffWeightLbs { get; set; }
        [Column("Zero Fuel Weight (lbs)")]
        public double? ZeroFuelWeightLbs { get; set; }
        [Column("Basic Operating Weight (lbs)")]
        public double? BasicOperatingWeightLbs { get; set; }
        [Column("Max# Landing Weight (lbs)")]
        public double? MaxLandingWeightLbs { get; set; }
        [Column("Vs Clean Speed Knots")]
        public double? VsCleanSpeedKnots { get; set; }
        [Column("Vso Landing Speed Knots")]
        public double? VsoLandingSpeedKnots { get; set; }
        [Column("Normal Cruise TAS Speed Knots")]
        public double? NormalCruiseTasSpeedKnots { get; set; }
        [Column("Vmo (Max Op) IAS Speed Knots")]
        public double? VmoMaxOpIasSpeedKnots { get; set; }
        [Column("Normal Climb (fpm)")]
        public double? NormalClimbFpm { get; set; }
        [Column("Engine Out Climb (fpm) ")]
        public double? EngineOutClimbFpm { get; set; }
        [Column("Ceiling (ft)")]
        public double? CeilingFt { get; set; }
        [Column("Landing Perf# FAA Field Length (ft)")]
        public double? LandingPerfFaaFieldLengthFt { get; set; }
        [Column("Takeoff Perf# SL ISA BFL")]
        public double? TakeoffPerfSlIsaBfl { get; set; }
        [Column("Takeoff Perf# 5000' +20C BFL")]
        public double? TakeoffPerf500020cBfl { get; set; }
        [Column("Range (nm)")]
        public double? RangeNm { get; set; }
        [Column("Number of engines")]
        public double? NumberOfEngines { get; set; }
        [Column("Engine Model(s)")]
        [StringLength(255)]
        public string EngineModelS { get; set; }
        [Column("Engine Thrust (lbs per Engine)")]
        public double? EngineThrustLbsPerEngine { get; set; }
        [Column("Engine Shaft (hp per Engine)")]
        public double? EngineShaftHpPerEngine { get; set; }
        [Column("Engine Common TBO Hours")]
        public double? EngineCommonTboHours { get; set; }
    }
}