// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using FBOLinx.Web.Models;

namespace FBOLinx.Web
{
    [Table("FBOFeesAndTaxes")]
    public partial class FboFeesAndTaxes
    {
        [Key]
        [Column("OID")]
        public int Oid { get; set; }
        [Column("FBOID")]
        public int Fboid { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public FBOLinx.Web.Enums.FeeCalculationTypes? CalculationType { get; set; }
        public double Value { get; set; }
        public FBOLinx.Web.Enums.FlightTypeClassifications? FlightTypeClassification { get; set; }
        public FBOLinx.Web.Enums.ApplicableTaxFlights? DepartureType { get; set; }
        public FBOLinx.Web.Enums.FeeCalculationApplyingTypes? WhenToApply { get; set; }

        #region Relationships
        [InverseProperty("FboFeeAndTax")]
        public List<FboFeeAndTaxOmitsByCustomer> OmitsByCustomer { get; set; }
        #endregion

        public double GetCalculatedValue(double basePrice, double allInPrice)
        {
            if (CalculationType == Enums.FeeCalculationTypes.FlatPerGallon)
                return Value;
            if (CalculationType == Enums.FeeCalculationTypes.Percentage)
                return (((Value / 100.0)) * basePrice);
            if (CalculationType == Enums.FeeCalculationTypes.PercentageOfTotal)
                return (((Value / 100.0)) * allInPrice);
            return Value;
        }
    }
}