use [paragon_test]
ALTER TABLE customers
ADD certificatetype smallint null
GO
update c set certificatetype=CASE WHEN CHARINDEX('corp', co.CertificateType) > 0 OR CHARINDEX('pers', co.CertificateType) > 0 OR CHARINDEX('non-business', co.CertificateType) > 0 OR CHARINDEX('test', co.CertificateType) > 0 OR			CHARINDEX('pri', co.CertificateType) > 0			THEN 91					WHEN CHARINDEX('char', co.CertificateType) > 0 OR CHARINDEX('part', co.CertificateType) > 0 OR CHARINDEX('rev', co.CertificateType) > 0 OR				(CHARINDEX('management', co.CertificateType) > 0 AND CHARINDEX('non-airline', co.CertificateType) > 0)			THEN 135		WHEN  ((CHARINDEX('management', co.CertificateType) > 0 AND CHARINDEX('non-airline', co.CertificateType) > 0) OR CHARINDEX('train', co.CertificateType) > 0 OR CHARINDEX('sched', co.CertificateType) > 0)			THEN 121		END from sqlfl.dbo.companies coinner join customers c on co.oid=c.fuelerlinxid or co.oid=-c.fuelerlinxidGOupdate cibg set certificatetype=c.certificatetypefrom customers cinner join customerinfobygroup cibg on cibg.customerid=c.oid and cibg.groupid>1GO
/****** Object:  StoredProcedure [dbo].[up_InsertUpdate_FBOContact]    Script Date: 8/19/2020 9:35:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--region [dbo].[up_InsertUpdate_FBOContact]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Burt using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[up_InsertUpdate_FBOContact]
-- Date Generated: Tuesday, June 26, 2012
------------------------------------------------------------------------------------------------------------------------

ALTER PROCEDURE [dbo].[up_InsertUpdate_FBOContact]
	@OID int = 0,
	@Email varchar(255),
	@FBOID int,
	@FirstName varchar(50),
	@LastName varchar(50),
	@Phone varchar(100),
	@Address varchar(255),
	@City varchar(255),
	@State varchar(10),
	@Country varchar(255),
	@Fax varchar(50),
	@Mobile varchar(50),
	@Title varchar(50),
	@Primary bit,
	@CopyAlerts bit,
	@Extension varchar(50) = '' 
AS

SET NOCOUNT ON

declare @ExistingContactID int

select @ExistingContactID = c.oid
from fbocontacts f
inner join contacts c on c.oid = f.contactid
inner join fbos fb on fb.oid = f.fboid
left join customercontacts cc on cc.contactid = c.oid
where fb.oid = @FBOID
and c.Email = @Email

if (isnull(@ExistingContactID, 0) > 0)
	begin
		SET @OID = @ExistingContactID
	end

IF EXISTS(SELECT [OID] FROM [dbo].[Contacts] WHERE [OID] = @OID)
BEGIN
	UPDATE [dbo].[Contacts] SET
		[Email] = @Email,
		[FirstName] = @FirstName,
		[LastName] = @LastName,
		[Phone] = @Phone,
		[Address] = @Address,
		[City] = @City,
		[State] = @State,
		[Country] = @Country,
		[Fax] = @Fax,
		[Mobile] = @Mobile,
		[Title] = @Title,
		[Primary] = @Primary,
		[CopyAlerts] = @CopyAlerts,
		Extension = @Extension
	WHERE
		[OID] = @OID
END
ELSE
BEGIN
	INSERT INTO [dbo].[Contacts] (
		[Email],
		[FirstName],
		[LastName],
		[Phone],
		[Address],
		[City],
		[State],
		[Country],
		[Fax],
		[Mobile],
		[Title],
		[Primary],
		[CopyAlerts],
		Extension
	) VALUES (
		@Email,
		@FirstName,
		@LastName,
		@Phone,
		@Address,
		@City,
		@State,
		@Country,
		@Fax,
		@Mobile,
		@Title,
		@Primary,
		@CopyAlerts,
		@Extension
	)
	
	SET @OID = @@IDENTITY
	
	INSERT INTO FBOContacts (FBOID, ContactID)
	values (@FBOID, @OID)
END

SELECT @OID
--endregion
GO

/****** Object:  StoredProcedure [dbo].[up_Load_Group]    Script Date: 8/6/2020 3:19:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--region [dbo].[up_Load_Fbo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Burt using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[up_Load_Fbo]
-- Date Generated: Tuesday, June 26, 2012
--*********************************************
--              Change History
--*********************************************
--  09/07/2013  CL Added in CustomCustomerType left join into the Customers select
--  09/13/2013  CL Added left join of FBOLogos into FBOs select
--  09/29/2013  CL Added in check for Active column in Customers select
--Chau Ly: 10/18/13- Left join RampFeeSettings
--  12/03/2013  CL Left join FBOPreferences
-- 01/16/2014	CL	Added in AddedFrom column for CustomerAircrafts query
-- 01/21/2014	CL	Added Domain column to SELECT Group query
-- 02/12/2014	CL	Changed CustomerType to include default CustomerType if Custom isn't available
-- 02/24/2014	CL	Changed HideInFBOLinx to not include Paragon
-- 03/27/2014	CL	Undid changes from 2/24/2014
-- 01/06/2015	CL	Added LoggedInHomePage
-- 03/28/2018	CL	Added in synonym for Dega table
------------------------------------------------------------------------------------------------------------------------

ALTER PROCEDURE [dbo].[up_Load_Group]
	@Username varchar(50) = '',
	@Password varchar(50) = '',
	@IsFBOLogin bit = 0,
	@GroupID int = 0
AS

declare @GroupName varchar(255) = ''
declare @FBOID int = null
declare @CustomerID int = 0
--Logintype: 1 = Group, 2 = FBO, 3 = Customer
declare @LoginType smallint = 0
declare @IsFBONetwork bit = 0
declare @Domain varchar(MAX) = ''
declare @LoggedInHomePage varchar(50) = ''

IF (ISNULL(@GroupID, 0) = 0)
BEGIN
	SELECT @GroupID = OID, @LoginType = 1, @IsFBONetwork = IsFBONetwork, @Domain = Domain, @LoggedInHomePage = LoggedInHomePage
	FROM [Group]
	WHERE Username = @Username
	AND [Password] = @Password
END
ELSE
BEGIN
	SET @LoginType = 1
END

IF (ISNULL(@GroupID, 0) = 0)
	BEGIN
		SELECT @GroupID = GroupID, @LoginType = 2, @FBOID = F.OID, @IsFBONetwork = IsFBONetwork, @Domain = Domain, @LoggedInHomePage = LoggedInHomePage
		FROM FBOs F
		inner join [Group] G ON G.OID = F.GroupID
		AND F.Username = @Username
		AND F.[Password] = @Password
		AND F.Active = 1
		and ISNULL(F.suspended, 0) = 0
	END

IF (ISNULL(@GroupID, 0) = 0)
	BEGIN
		SELECT @GroupID = C.GroupID, @LoginType = 3, @CustomerID = C.CustomerID
		FROM CustomerInfoByGroup C
		WHERE C.Username = @Username
		AND C.Password = @Password
		and ISNULL(suspended, 0) = 0
		and ISNULL(active,0) = 1
	END

IF (ISNULL(@GroupID, 0) > 0 AND @IsFBOLogin = 1)
BEGIN
		SELECT @GroupID = GroupID, @LoginType = 2, @FBOID = F.OID, @IsFBONetwork = IsFBONetwork, @Domain = Domain, @LoggedInHomePage = LoggedInHomePage
		FROM FBOs F
		inner join [Group] G ON G.OID = F.GroupID
		AND G.OID = @GroupID
		AND F.Active = 1
		and ISNULL(F.suspended, 0) = 0
	END
	
SELECT @GroupID = G.OID,
		@GroupName = G.[Group],
		@IsFBONetwork = G.IsFBONetwork,
		@Domain = G.Domain
FROM [Group] G
WHERE (G.Username = @Username AND G.Password = @Password AND @GroupID < 1)
OR (@GroupID > 0 AND G.OID = @GroupID)

IF (@GroupID > 0)
BEGIN
	--Update last login if login is FBO
	IF (@LoginType = 2)
	BEGIN
	UPDATE FBOs
	SET LastLogin = GETDATE()
	WHERE OID = @FBOID
	END
	
	--Group information
	SELECT @GroupID AS GroupID, 
			@GroupName AS GroupName, 
			@LoginType AS LoginType,
			@CustomerID AS CustomerID,
			@FBOID AS FBOID,
			@IsFBONetwork AS IsFBONetwork,
			@Domain AS Domain,
			@LoggedInHomePage AS LoggedInHomePage
	
	--FBOs for the group
	SELECT F.*, FST.FBOID, FST.SalesTax100LLDecimal, FST.SalesTaxDecimal, FL.LogoFilename, RFS.HasRampFees, FP.CostCalculator, FP.Omit100LLCost, FP.Omit100LLRetail, FP.OmitJetACost, FP.OmitJetARetail
	FROM FBOs F
	LEFT JOIN FBOSalesTax FST ON FST.FBOID = F.OID
	LEFT JOIN FBOLogos FL ON FL.FBOID = F.OID
	LEFT JOIN RampFeeSettings RFS ON RFS.FBOID = F.OID
	LEFT JOIN FBOPreferences FP ON FP.FBOID = F.OID
	WHERE GroupID = @GroupID
	
	--FBO contacts
	SELECT FC.FBOID, FC.ContactID, C.[Address], C.City, C.CopyAlerts, C.Country, C.Email, C.Extension, C.Fax, C.FirstName, C.LastName, C.Mobile,
	    C.Phone, C.[Primary], C.[State], C.Title, C.OID
	FROM FBOContacts FC
	INNER JOIN Contacts C ON C.OID = FC.ContactID
	INNER JOIN FBOs F ON F.OID = FC.FBOID
	WHERE F.GroupID = @GroupID
	
	--FBO locations
	SELECT FL.FBOID, FL.OID, FL.DefaultTemplate, A.*
	FROM FBOAirports FL
	INNER JOIN FBOs F ON F.OID = FL.FBOID
	LEFT JOIN DEGA_Airports A ON A.ICAO = FL.ICAO
	WHERE F.GroupID = @GroupID
	
	--Customers for the group
	SELECT C.[Action], C.Margin, C.Pilot, C.Title, C.CheckFuelPrice, C.Lastlogin, C.OID, C.FuelerlinxID,
	CIG.Active, CIG.[Address], CIG.CertificateType, CIG.City, CIG.Company, CIG.Country, CIG.CustomerCompanyType, CIG.CustomerID, CIG.CustomerType, CIG.DefaultTemplate,
	CIG.Distribute, CIG.EmailSubscription, CIG.GroupID, CIG.Joined, CIG.MainPhone, CIG.Network, CIG.[Password], CIG.SFID, CIG.Show100LL, CIG.ShowJetA, CIG.[State],
	CIG.Suspended, CIG.Username, CIG.Website, CIG.ZipCode
	,ISNULL(CCT.CustomerType, ISNULL(CIG.[CustomerType], 0)) AS CustomerType,
      ISNULL(CIG.[CustomerType], 0) AS DefaultCustomerType
	FROM Customers AS C
	INNER JOIN CustomerInfoByGroup AS CIG ON CIG.CustomerID = C.OID AND CIG.GroupID = @GroupID
	LEFT JOIN CustomCustomerTypes AS CCT ON (CCT.CustomerID = CIG.CustomerID AND CCT.FBOID = @FBOID)
	LEFT JOIN FUELERLINX_Companies AS Co ON Co.OID = C.FuelerlinxID OR Co.OID = -C.FuelerlinxID
	WHERE ISNULL(Co.HideInFboLinx, 0) = 0
	ORDER BY CIG.Company
	
	--Customer contacts
	SELECT CC.ContactID, CC.CustomerID, CIG.[Address], CIG.City, CIG.ContactID, CIG.CopyAlerts, CIG.Country, CIG.Email, CIG.Extension, CIG.Fax, CIG.FirstName,
	    CIG.GroupID, CIG.LastName, CIG.Mobile, CIG.Phone, CIG.[Primary], CIg.[State], CIg.Title,
	    Co.OID
	FROM CustomerContacts CC
	INNER JOIN Customers C ON C.OID = CC.CustomerID
	INNER JOIN Contacts Co ON Co.OID = CC.ContactID
	INNER JOIN ContactInfoByGroup CIG ON CIG.ContactID = Co.OID AND CIG.GroupID = @GroupID
	
	--Aircraft for the customer
	SELECT CA.OID,
			CA.GroupID,
			CA.CustomerID,
			CA.TailNumber,
			CA.BasedPAGLocation,
			CA.NetworkCode,
			AC.AircraftID,
			AC.MAKE AS AircraftMake,
			AC.MODEL AS AircraftModel,
			AC.[NORMAL CRUISE TAS] AS NormalCruiseTAS,
			AC.[FUEL CAPACITY (gal)] AS FuelCapacity,
			AC.[LANDING PERF LENGTH] AS LandingPerfLength,
			AC.[RANGE (nm)] AS MaxRange,
			AC.MaxRangeHours AS MaxRangeHours,
			AC.MaxRangeMinutes AS MaxRangeMinutes,
			AC.RangePerGal AS RangePerGal,
			AC.ReserveMinutes AS ReserveMinutes,
			AC.ReserveNM AS ReserveNM,
			CASE WHEN ISNULL(CA.Size, 0) > 0
							THEN CA.Size
							ELSE ISNULL(AC.Size, 0) END AS Size,
			CASE WHEN ISNULL(AC.MaxRangeHours, 0) > 0 THEN ISNULL(AC.[FUEL CAPACITY (gal)], 0) / ISNULL(AC.MaxRangeHours, 1) ELSE 0 END AS FuelBurnRate,
			AC.FuelType AS FuelType,
			CA.AddedFrom
	FROM
	CustomerAircrafts CA
	LEFT JOIN DEGA_airCrafts AC ON AC.AircraftID = CA.AircraftID
	INNER JOIN Customers C ON C.OID = CA.CustomerID
	LEFT JOIN FUELERLINX_Companies AS Co ON Co.OID = C.FuelerlinxID
	WHERE CA.GroupID = @GroupID AND ISNULL(Co.HideInFboLinx, 0) = 0
	ORDER BY CA.TailNumber
	
	--Admin emails for the group
	
	SELECT *
	FROM AdminEmails
	WHERE GroupID = @GroupID
	
	SELECT RF.*, FBO.[Fbo]
      ,FBO.[GroupID]
      ,FBO.[Username]
      ,FBO.[Password]
      ,FBO.[PostedRetail]
      ,FBO.[TotalCost]
      ,FBO.[Active]
      ,FBO.[DateActivated]
      ,FBO.[Address]
      ,FBO.[City]
      ,FBO.[State]
      ,FBO.[ZipCode]
      ,FBO.[Country]
      ,FBO.[TotalCost100LL]
      ,FBO.[PostedRetail100LL]
      ,FBO.[Suspended]
      ,FBO.[GroupMargin]
      ,FBO.[ApplyGroupMargin]
      ,FBO.[GroupMarginSetting]
      ,FBO.[GroupMarginFuture]
      ,FBO.[GroupMarginTemplate]
      ,FBO.[GroupMarginMargin]
      ,FBO.[GroupMarginType]
      ,FBO.[GroupMargin100LLMargin]
      ,FBO.[GroupMargin100LLType]
      ,FBO.[FuelDeskEmail]
      ,FBO.[MainPhone]
      ,FBO.[Extension]
      ,FBO.[DefaultMarginTypeJetA]
      ,FBO.[DefaultMarginType100LL]
      ,FBO.[SalesTax]
      ,FBO.[ApplySalesTax]
      ,FBO.[LastLogin]
      ,FBO.[PriceUpdateReminderPrompt]
      ,FBO.[PriceUpdateNeverPrompt]
      ,FBO.[Currency]
      ,FBO.[InitialSetupPhase]
      ,FBO.[DisableCost]
	FROM RampFees AS RF
	INNER JOIN FBOs FBO ON RF.FBOID = FBO.OID AND FBO.GroupID = @GroupID AND ISNULL(RF.Size, 0) > 0
	
	--FBO Prices
	EXEC up_Load_FBOPrices @GroupID
	
	--Customer margins
	EXEC up_Load_CustomerMargins @GroupID = @GroupID
END
GO
/****** Object:  StoredProcedure [dbo].[up_Update_FuelerlinxCompany]    Script Date: 8/31/2020 5:20:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Mike Mieglitz
-- Create date: 02/27/2013
-- Description:	Update a company tied to Fuelerlinx based on their account status
--*********************************************
--              Change History
--*********************************************
--  09/24/2013  CL  Added in queries to add CustomerInfoByGroup records if company was deleted while they were deactivated from FuelerLinx; add in current aircrafts
--  09/26/2013  CL	Changed query to use FuelerLinxID instead of FBOlinxID when updating Customers table so that it'd grab records for Paragon/Generic FBOlinx, in case there were duplicates 
--  10/09/2013  CL	Changed Distribute flag from 0 to 1 when adding new FuelerLinx customers
--  10/29/2013  CL	Added in an update for Company for CustomerInfoByGroup
--  11/06/2013	CL	Added COALESCE(@Company, CG.Company) when updating Company name to prevent blanks for inserting/updating
--  11/18/2013  CL	Set Distribute = 1 when updating current FuelerLinx customers
--	01/16/2014	CL	Added in AddedFrom column for CustomerAircrafts query
--	08/01/2017	CL	Changed SP to use local variables instead
--	11/17/2017	CL	Added and @Local_FuelerlinxCompanyID <> 0
-- =============================================
ALTER PROCEDURE [dbo].[up_Update_FuelerlinxCompany]
	@FuelerlinxCompanyID int,
	@FBOLinxCompanyID int = null,
	@Company varchar(50) = null
AS
BEGIN
	declare @Local_FuelerlinxCompanyID int
	declare @Local_FBOLinxCompanyID int
	declare @Local_Company varchar(50)

	SET @Local_FuelerlinxCompanyID = @FuelerlinxCompanyID
	SET @Local_FBOLinxCompanyID = @FBOLinxCompanyID
	SET @Local_Company = @Company

	if (@Local_FBOLinxCompanyID is null)
		SELECT @Local_FBOLinxCompanyID = OID FROM Customers WHERE FuelerlinxID = @Local_FuelerlinxCompanyID
	
	IF (ISNULL(@Local_FBOLinxCompanyID, 0) > 0 and @Local_FuelerlinxCompanyID <> 0)
		BEGIN
			IF (EXISTS(SELECT OID FROM FUELERLINX_custData WHERE active = 1 and companyID = @Local_FuelerlinxCompanyID))
				BEGIN
					IF (@Local_FBOLinxCompanyID > 0)
						UPDATE Customers
						SET FuelerlinxID = @Local_FuelerlinxCompanyID
						WHERE FuelerLinxID = -@Local_FuelerlinxCompanyID
						
						UPDATE CG
						SET Distribute = 1, CustomerType = 1, Company = COALESCE(@Local_Company, CG.Company)
						FROM CustomerInfoByGroup CG
						INNER JOIN Customers C 
						ON C.FuelerlinxID = @Local_FuelerlinxCompanyID
						and C.OID = CG.CustomerID
						
						INSERT INTO CustomerInfoByGroup (GroupID, CustomerID, Company, Active, Distribute, Network, ShowJetA, Show100LL, Suspended, CustomerType, CertificateType)
						SELECT G.OID, @Local_FBOLinxCompanyID, @Local_Company, 1, 1, 0, 1, 0, 0, 1, CustCertificateType
						FROM [Group] G
						LEFT JOIN 
							(select CIBG.*, C.CertificateType as CustCertificateType from CustomerInfoByGroup CIBG
							 inner join Customers C on C.OID = CIBG.CustomerID and C.FuelerlinxID = @Local_FuelerlinxCompanyID) CC ON G.OID = CC.GroupID
						WHERE CC.CustomerID IS NULL
						
						INSERT INTO CustomerAircrafts (TailNumber, CustomerID, AircraftID, Size, GroupID, AddedFrom)
						SELECT AC.tailNo, C.OID, AC.AircraftID, AC.Size, CG.GroupID, 1
						FROM Customers C
						INNER JOIN CustomerInfoByGroup CG ON CG.CustomerID = C.OID
						INNER JOIN FUELERLINX_UserAircraft UA ON UA.CompanyID = @Local_FuelerlinxCompanyID
						INNER JOIN FUELERLINX_acData2 AC ON AC.OID = UA.TailNumID
						LEFT JOIN CustomerAircrafts CA ON CA.TailNumber = AC.tailNo
																		AND C.OID = CA.CustomerID
																		AND CA.GroupID = CG.GroupID
						WHERE C.FuelerlinxID = @Local_FuelerlinxCompanyID
							AND CA.OID IS NULL
						GROUP BY AC.tailNo, C.OID, AC.AircraftID, AC.Size, CG.GroupID
				END
			ELSE
				BEGIN
					UPDATE CG
					SET Distribute = 1, CustomerType = 3
					FROM CustomerInfoByGroup CG
					INNER JOIN Customers C 
					ON C.FuelerlinxID = @Local_FuelerlinxCompanyID
					and C.OID = CG.CustomerID
				
					UPDATE Customers
					SET FuelerlinxID = -@Local_FuelerlinxCompanyID,
						Distribute = 1
					WHERE FuelerlinxID = @Local_FuelerlinxCompanyID
				END
		END
END
GO