// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using FBOLinx.DB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace FBOLinx.Web
{
    public partial class Dega_LocalContext : DbContext
    {
        public Dega_LocalContext()
        {
        }

        public Dega_LocalContext(DbContextOptions<Dega_LocalContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AirportWatchHistoricalData> AirportWatchHistoricalData { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AirportWatchHistoricalData>(entity =>
            {
                entity.Property(e => e.AircraftHexCode).IsUnicode(false);

                entity.Property(e => e.AircraftTypeCode).IsUnicode(false);

                entity.Property(e => e.AtcFlightNumber).IsUnicode(false);

                entity.Property(e => e.BoxName).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}