use [paragon_test]

CREATE NONCLUSTERED INDEX [indx_DistributionQueue_GroupID_FBOID_CustomerID] ON [dbo].[DistributionQueue]
(
	[GroupID] ASC,
	[FBOID] ASC,
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
USE [paragon_test]
GO
/****** Object:  StoredProcedure [dbo].[up_Delete_Fbo]    Script Date: 3/29/2023 2:57:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--region [dbo].[up_Delete_Fbo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Burt using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[up_Delete_Fbo]
-- Date Generated: Tuesday, June 26, 2012
------------------------------------------------------------------------------------------------------------------------

ALTER PROCEDURE [dbo].[up_Delete_Fbo]
	@OID int
AS

SET NOCOUNT ON

--declare @OID int =1007
DELETE FROM AuditsLogs where FBOID = @OID

DELETE FROM CustomCustomerTypes WHERE FBOID = @OID

DELETE FROM CustomerCompanyTypes WHERE FBOID = @OID

--DELETE FROM CustomerDefaultTemplates WHERE FBOID = @OID

DELETE FROM CustomersViewedByFbo WHERE FBOID=@OID

DELETE FROM DistributionLog WHERE FBOID=@OID

DELETE FROM DistributionQueue WHERE FBOID=@OID

DELETE FROM EmailContent WHERE FBOID=@OID

--DELETE FROM FboaircraftSizes WHERE FBOID=@OID

DELETE FROM Fboairports WHERE FBOID=@OID

DELETE C
FROM Contacts C
INNER JOIN FBOContacts F on F.ContactID = C.OID
WHERE F.FBOID = @OID

DELETE FROM Fbocontacts WHERE FBOID=@OID

DELETE FROM Fbopreferences WHERE FBOID=@OID

DELETE FROM Fboprices WHERE FBOID=@OID

--DELETE FROM NetworkNotes WHERE FBOID=@OID

DELETE C
FROM CustomerMargins C
INNER JOIN PricingTemplate P ON P.OID = C.TemplateID
WHERE P.FBOID = @OID

DELETE FROM PricingTemplate WHERE FBOID=@OID

DELETE FROM RampFees WHERE FBOID=@OID

DELETE FROM RampFeeSettings WHERE FBOID=@OID

DELETE FROM TempAddOnMargin WHERE FBOID=@OID

DELETE FROM [User] WHERE FBOID=@OID

--DELETE FROM VolumeScaleDiscount WHERE FBOID=@OID

--DELETE FROM ContractFuelRelationships WHERE FBOID=@OID

--DELETE FROM DefaultDiscount WHERE FBOID=@OID

--DELETE FROM DistributionEmailsBody WHERE FBOID=@OID

--DELETE FROM FbocustomerPricing WHERE FBOID=@OID

DELETE FROM Fbologos WHERE FBOID=@OID

--DELETE FROM FbosalesTax WHERE FBOID=@OID

DELETE FROM FuelReq WHERE FBOID=@OID

--DELETE FROM PriceHistory WHERE FBOID=@OID

--DELETE FROM ReminderEmailsToFbos WHERE FBOID=@OID

--DELETE FROM RequestPricingTracker WHERE FBOID=@OID

DELETE FROM FileStorage.dbo.FboLinxImageFileData WHERE FBOID = @OID

DELETE FROM IntegrationStatus WHERE FBOID = @OID

DELETE FROM IntegrationUpdatePricingLog WHERE FBOID = @OID

DELETE FROM MissedQuoteLog WHERE FBOID = @OID

DELETE FROM Fbos WHERE OID=@OID
GO
USE [paragon_test]
GO
/****** Object:  StoredProcedure [dbo].[up_Delete_Group]    Script Date: 3/29/2023 1:39:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[up_Delete_Group]
	@OID int
AS

SET NOCOUNT ON

DELETE FROM CompaniesByGroup WHERE GroupId = @OID

DELETE FROM ContactInfoByGroup WHERE GroupId = @OID

DELETE FROM CustomerAircrafts WHERE GroupId = @OID

--DELETE FROM CustomerCompanyTypes WHERE GroupId = @OID

DELETE FROM CustomerInfoByGroup WHERE GroupId = @OID

DELETE FROM DistributionLog WHERE GroupId = @OID

DELETE FROM DistributionQueue WHERE GroupId = @OID

--DELETE FROM MappingPrices WHERE GroupId = @OID

DELETE FROM [User] WHERE GroupId = @OID

DELETE FROM AdminEmails WHERE GroupId = @OID

--DELETE FROM CustomerAircraftViewedByGroup WHERE GroupId = @OID

--DELETE FROM CustomerNotes WHERE GroupId = @OID

--DELETE FROM CustomerSchedulingSoftwareByGroup WHERE GroupId = @OID

--DELETE FROM Jobs WHERE GroupId = @OID

--DELETE FROM NetworkNotes WHERE GroupId = @OID
GO
