// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using FBOLinx.DB.Models;

namespace FBOLinx.DB.Context
{
    public partial class FilestorageContext : DbContext
    {
        public FilestorageContext()
        {
        }

        public FilestorageContext(DbContextOptions<FilestorageContext> options)
            : base(options)
        {
        }

        public virtual DbSet<FboLinxImageFileData> FboLinxImageFileData { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FboLinxImageFileData>(entity =>
            {
                entity.Property(e => e.ContentType).IsUnicode(false);

                entity.Property(e => e.FileName).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}