// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FBOLinx.DB
{
    public partial class ContactInfoByFbo
    {
        [Key]
        public int Oid { get; set; }
        public int? ContactId { get; set; }
        public int? FboId { get; set; }
        public bool? CopyAlerts { get; set; }
    }
}