use [paragon_test]
GO
ALTER TABLE AirportWatchHistoricalData
ADD AirportICAO varchar(255) null
GO
delete a
FROM [CustomerAircrafts] AS [c]
INNER JOIN [AircraftPrices] AS [a] ON [c].[OID] = [a].[CustomerAircraftID]
inner join PricingTemplate pt on pt.oid = a.PriceTemplateID
left join FBOs f on f.oid = pt.fboid and f.groupid = c.Groupid
where f.OID is null
GO
/****** Object:  StoredProcedure [dbo].[up_InsertUpdate_AircraftPrices]    Script Date: 3/2/2021 11:29:35 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--region [dbo].[up_InsertUpdate_PriceTier]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Burt using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[up_InsertUpdate_AircraftPrices]
-- Date Generated: 8/1/2012
--*********************************************
--              Change History
--*********************************************
--  09/19/2013  CL  Added Insert AircraftPrices for each FBO in group for non-Paragon
--  10/01/2013  CL  Added GroupID > 1 into Insert AircraftPrices for non-Paragon
--  10/31/2013  CL  Added ISNULL(A.OID, 0) = 0 to non-Paragon SQL to fix bug of trying to add duplicate records
--  02/25/2014  CL  Added in delete query for AircraftPrices with OID of 0 in order to prevent duplicate records
------------------------------------------------------------------------------------------------------------------------

ALTER PROCEDURE [dbo].[up_InsertUpdate_AircraftPrices]
	@AircraftPrices AircraftPriceType2 READONLY
AS
BEGIN
	DELETE AP
	FROM AircraftPrices AP
	INNER JOIN @AircraftPrices A ON A.CustomerAircraftID = AP.CustomerAircraftID
	INNER JOIN PricingTemplate pt on pt.OID = A.PriceTemplateID AND pt.OID = AP.PriceTemplateID
	INNER JOIN FBOs F on pt.FBOID = F.OID
	WHERE ISNULL(A.OID, 0) = 0

	INSERT INTO AircraftPrices (CustomerAircraftID, PriceTemplateID, CustomTemplate)
	SELECT CustomerAircraftID, PriceTemplateID, CustomTemplate
	FROM @AircraftPrices
	WHERE ISNULL(OID , 0) = 0

	UPDATE AP
	SET CustomerAircraftID = A.CustomerAircraftID,
		PriceTemplateID = A.PriceTemplateID,
		CustomTemplate = A.CustomTemplate
	FROM AircraftPrices AP
	INNER JOIN @AircraftPrices A ON A.OID = AP.OID
END
GO
/****** Object:  StoredProcedure [dbo].[up_InsertUpdate_PricingTemplate]    Script Date: 3/2/2021 11:40:10 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--region [dbo].[up_InsertUpdate_PricingTemplate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Burt using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[up_InsertUpdate_PricingTemplate]
-- Date Generated: Monday, July 30, 2012
------------------------------------------------------------------------------------------------------------------------

ALTER PROCEDURE [dbo].[up_InsertUpdate_PricingTemplate]
	@OID int,
	@Name varchar(500),
	@FBOID int,
	@CustomerID int,
	@Default bit,
	@Notes varchar(MAX),
	@Type smallint = 0,
	@MarginType int = 0
AS

SET NOCOUNT ON

DECLARE @NumberOfTemplates int = 0
DECLARE @GroupID int = 1

IF EXISTS(SELECT [OID] FROM [dbo].[PricingTemplate] WHERE [OID] = @OID)
BEGIN
	UPDATE [dbo].[PricingTemplate] SET
		[Name] = @Name,
		[FBOID] = @FBOID,
		[CustomerID] = @CustomerID,
		[Default] = @Default,
		[Notes] = @Notes,
		[Type] = @Type,
		MarginType = @MarginType
	WHERE
		[OID] = @OID
END
ELSE
BEGIN
	INSERT INTO [dbo].[PricingTemplate] (
		[Name],
		[FBOID],
		[CustomerID],
		[Default],
		[Notes],
		[Type],
		MarginType
	) VALUES (
		@Name,
		@FBOID,
		@CustomerID,
		@Default,
		@Notes,
		@Type,
		@MarginType
	)
	SET @OID = @@IDENTITY
	
	--New price template for an FBO.  Insert it for all aircraft
	--SELECT @NumberOfTemplates = COUNT (F.GroupID), @GroupID = F.GroupID
	--FROM PricingTemplate PT
	--INNER JOIN FBOs F
	--	ON F.OID = @FBOID AND F.OID = PT.FBOID AND F.GroupID > 1
	--Group By F.GroupID

	--IF (@Default = 1 OR @NumberOfTemplates = 1)
	--	BEGIN
	--		INSERT INTO AircraftPrices (CustomerAircraftID, PriceTemplateID)
	--		SELECT OID, @OID
	--		FROM CustomerAircrafts
	--		WHERE GroupID = @GroupID
	--	END
END

SELECT @OID AS OID

--endregion
GO
USE [paragon_test]
GO
/****** Object:  Table [dbo].[AirportWatchChangeTracker]    Script Date: 3/4/2021 10:25:23 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AirportWatchChangeTracker](
	[OID] [int] IDENTITY(1,1) NOT NULL,
	[LiveDataRecords] [int] NULL,
	[HistoricalDataRecords] [int] NULL,
	[TailNumberRecords] [int] NULL,
	[DateTimeAppliedUTC] [datetime2](7) NULL,
 CONSTRAINT [PK_AirportWatchChangeTracker] PRIMARY KEY CLUSTERED 
(
	[OID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO